[package]
name = "mermaid-parser"
version = "0.1.0"
edition = "2021"
description = "A Rust parser for Mermaid diagrams"
license = "MIT"
repository = "https://github.com/your-username/mermaid-parser"

[dependencies]
chumsky = "0.10.1"

[dev-dependencies]
rstest = "0.21"
